### ISSUE TITLE
Unable to load any entities

### ISSUE THREAD

**Issue by maslyankov** [nielsrowinbik/auto-sections-strategy#1]
**Describe the bug**
Hi! I wanted to try out the strategy but nothing shows up.

**To Reproduce**
Installed and configured with this config:
```
views:
  - strategy:
      type: custom:auto-sections
      options:
        max_columns: 3
        group_by:
          - device.area_id
          - entity.area_id
        group_name: area.area_id|name
        filter:
          include:
            - domain: light
            - domain: switch
            - domain: climate
            - state: 'on'
          exclude:
            - hidden: true
        show_empty: false
        card_options:
          _:
            type: entity
```

The result is a blank view.

**Expected behavior**
Show entities.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nielsrowinbik** [comment]
Hi @maslyankov, sorry for the late reply. Are you including `layout: sections` in your dashboard configuration? The correct (full) configuration in your case would be:

```yaml
layout: sections
views:
  - strategy:
      type: custom:auto-sections
      options:
        max_columns: 3
        group_by:
          - device.area_id
          - entity.area_id
        group_name: area.area_id|name
        filter:
          include:
            - domain: light
            - domain: switch
            - domain: climate
            - state: 'on'
          exclude:
            - hidden: true
        show_empty: false
        card_options:
          _:
            type: entity
```

**Comment by maslyankov** [comment]
> Hi @maslyankov, sorry for the late reply. Are you including `layout: sections` in your dashboard configuration? The correct (full) configuration in your case would be:
> 
> ```yaml
> layout: sections
> views:
>   - strategy:
>       type: custom:auto-sections
>       options:
>         max_columns: 3
>         group_by:
>           - device.area_id
>           - entity.area_id
>         group_name: area.area_id|name
>         filter:
>           include:
>             - domain: light
>             - domain: switch
>             - domain: climate
>             - state: 'on'
>           exclude:
>             - hidden: true
>         show_empty: false
>         card_options:
>           _:
>             type: entity
> ```

Thanks for the suggestion. It does seem to load the strategy, as it shows errors if I remove any part of the required config, but does not show any feedback visually or in the console:

```
layout: sections
views:
  - strategy:
      type: custom:auto-sections
      options:
        max_columns: 3
        group_name: area.area_id|name
        group_by:
          - device.area_id
          - entity.area_id
        filter:
          include:
            - domain: light
            - domain: switch
            - domain: climate
        show_empty: false
        card_options:
          _:
            type: entities

```
![Uploading Screenshot 2024-05-11 at 7.58.47 PM.png…]()
