### ISSUE TITLE
[Feature Request] Areas order, Floors support?, Add support for "unassigned to area" entities

### ISSUE THREAD

**Issue by maslyankov** [nielsrowinbik/auto-sections-strategy#8]
Some nice to have features:
- Be able to order areas in some way
- Segmenting things by floors can be useful too
- Support for "unassigned to area" entities
- Exclude specific areas
- Add custom section at top/bottom

**Comment by nielsrowinbik** [comment]
- What ways of ordering sections are you looking for? Right now it does alphabetically by default, what else would you like to see it do?
- Would you expect the strategy to be able to create a section per floor? Depending on how entities are linked to floors, this may already be possible.
- Fundamentally, this strategy already supports entities not tied to an area, just not when grouping by area, if that makes sense. Are you looking to have like a catch all group for all entities not tied to an area when grouping by area?
- Excluding certain areas is a good idea, I'll add a filter for it
- Adding sections at the top or bottom should be easy to implement, so I'll get on that soon-ish.

**Comment by nielsrowinbik** [comment]
@maslyankov  I just pushed 0.6.0 which includes an area filter and the ability to add custom sections to the top or bottom of the generated list. It's also got a breaking change in that I removed some unused configuration items.

**Comment by maslyankov** [comment]
> * What ways of ordering sections are you looking for? Right now it does alphabetically by default, what else would you like to see it do?
> * Would you expect the strategy to be able to create a section per floor? Depending on how entities are linked to floors, this may already be possible.
> * Fundamentally, this strategy already supports entities not tied to an area, just not when grouping by area, if that makes sense. Are you looking to have like a catch all group for all entities not tied to an area when grouping by area?
> * Excluding certain areas is a good idea, I'll add a filter for it
> * Adding sections at the top or bottom should be easy to implement, so I'll get on that soon-ish.

- Not sure how it would be best to configure that, but something like:

**Comment by maslyankov** [comment]
I managed to make use of the custom top sections like so:

```
layout: sections
views:
  - title: Main
    strategy:
      type: custom:auto-sections
      options:
        max_columns: 2
        group_by:
          - device.area_id
          - entity.area_id
        group_name: area.area_id|name
        filter:
          include:
            - hidden: false
        sections:
          top:
            - type: grid
              cards:
                - type: markdown
                  content: '# {{ state_attr("zone.home", ''friendly_name'') }}'
                - type: conditional
                  conditions:
                    - condition: state
                      entity: input_boolean.ui_home_show_weather
                      state: 'on'
                  card:
                    type: custom:auto-entities
                    card:
                      type: custom:layout-card
                      layout_type: masonry
                      layout:
                        margin: 0
                        card_margin: 0
                      cards: []
                      view_layout: {}
                    filter:
                      exclude: []
                      include:
                        - domain: weather
                          options:
                            type: custom:auto-entities
                            card:
                              type: custom:layout-card
                            filter:
                              template: |
                                {{ [
                                  {
                                    "type": "weather-forecast",
                                    "forecast_type": "daily",
                                    "entity": config.entity
                                  }
                                ] }}
                - type: conditional
                  conditions:
                    - condition: state
                      entity: input_boolean.ui_home_show_alarm_panels
                      state: 'on'
                  card:
                    type: custom:auto-entities
                    card:
                      type: custom:layout-card
                      layout_type: masonry
                      layout:
                        margin: 0
                        card_margin: 0
                      cards: []
                      view_layout: {}
                    filter:
                      exclude: []
                      include:
                        - domain: alarm_control_panel
                          options:
                            type: custom:auto-entities
                            card:
                              type: custom:layout-card
                            filter:
                              template: |
                                {{ [
                                  {                        
                                    "type": "tile",
                                    "entity": config.entity,
                                    "features": [
                                      {
                                        "type": "alarm-modes",
                                        "modes": ["armed_home", "armed_away", "armed_night", "armed_vacation", "armed_custom_bypass", "disarmed"]
                                      }
                                    ]
                                  }
                                ] }}                  
        card_options:
          _:
            type: tile
          alarm_control_panel:
            features:
              - type: alarm-modes
                modes:
                  - armed_home
                  - armed_away
                  - armed_night
                  - armed_vacation
                  - armed_custom_bypass
                  - disarmed
          climate:
            features:
              - type: target-temperature
              - type: climate-fan-modes
                style: icons
                fan_modes:
                  - 'off'
                  - low
                  - medium
                  - high
                  - on_low
                  - on_high
                  - auto_low
                  - auto_high
              - type: climate-hvac-modes
                hvac_modes:
                  - auto
                  - heat_cool
                  - heat
                  - cool
                  - dry
                  - fan_only
                  - 'off'
          cover:
            features:
              - type: cover-open-close
          lawn_mower:
            features:
              - type: lawn-mower-commands
                commands:
                  - start_pause
                  - dock
          light:
            features:
              - type: light-brightness
          lock:
            features:
              - type: lock-commands
          media_player:
            type: media-control
          camera:
            show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
```

This allows me to show and hide info from the top using input_booleans and thus being easily configurable. The issue is that by using it this way these auto-entities cards render with delay after the whole view. Do you have an idea how we can fix this or integrate something like this in a better way? Thanks!
