### ISSUE TITLE
Exclude areas affecting entities, whose parent device is in excluded area

### ISSUE THREAD

**Issue by maslyankov** [nielsrowinbik/auto-sections-strategy#9]
**Describe the bug**
Exclude areas affecting entities, whose parent device is in excluded area

**To Reproduce**

```
layout: sections
views:
  - title: Main
    icon: mdi:home
    strategy:
      type: custom:auto-sections
      options:
        max_columns: 2
        group_by:
          - entity.area_id
          - area.area_id
        group_name: area.area_id|name
        filter:
          include:
            - hidden: false
          exclude:
            - area: services
        card_options:
          _:
            type: tile
```

Lets say we have a DVR in area "Services", and it has cameras as entities under that device. Some cameras are assigned another area, despite that, they are not shown, because of the exclude affecting the device and child entities.

**Expected behavior**
Hide only entities in excluded area.

**Possible solution**
Make filters more fine-grained as so:

```
layout: sections
views:
  - title: Main
    icon: mdi:home
    strategy:
      type: custom:auto-sections
      options:
        max_columns: 2
        group_by:
          - entity.area_id
          - area.area_id
        group_name: area.area_id|name
        filter:
          include:
            - entity.hidden: false
          exclude:
            - entity.area: services
        card_options:
          _:
            type: tile
```
